Crud/Crud-war/src/java/controller/UsuarioController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package controller;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import java.util.*;
import javax.ejb.EJB;
import model.UsuariosFacade;
import entities.*;

/**
 *
 * @author cristiandulcey
 */
@ManagedBean
@SessionScoped
public class UsuarioController {
    @EJB
    private UsuariosFacade usuariosFacade;
    private Usuarios U=new Usuarios();

    public Usuarios getU() {
        return U;
    }

    public void setU(Usuarios U) {
        this.U = U;
    }
    
   
    public UsuarioController() {
    }
    
    public List<Usuarios> findAll(){
        return this.usuariosFacade.findAll();
    }
    public String add(){
       this.usuariosFacade.create(this.U);
       this.U =new Usuarios();
       return "index";
   }
    public void delete(Usuarios U){
        this.usuariosFacade.remove(U);
    }
    public String edit(Usuarios U){
        this.U=U;
        return "editar";
    } 
    public String edit(){
        this.usuariosFacade.edit(this.U);
        return "index";
    } 
    
}

Crud/Crud-war/web/agregar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Nuevo Usuario</title>
    </h:head>
    <h:body>
        <f:view>
            <h:form>
                <h1><h:outputText value="Crear"/></h1>
                <h:panelGrid columns="2">
                    <h:outputLabel value="Cod:" for="cod" />
                    <h:inputText id="cod" value="#{usuarioController.u.cod}" title="Cod" required="true" requiredMessage="The Cod field is required."/>
                    <h:outputLabel value="Nom:" for="nom" />
                    <h:inputText id="nom" value="#{usuarioController.u.nom}" title="Nom" />
                    <h:outputLabel value="Edad:" for="edad" />
                    <h:inputText id="edad" value="#{usuarioController.u.edad}" title="Edad" />
                    <h:outputLabel value="Tel:" for="tel" />
                    <h:inputText id="tel" value="#{usuarioController.u.tel}" title="Tel" />
                    <h:commandButton value="Guardar" action="#{usuarioController.add()}"></h:commandButton>
                </h:panelGrid>
            </h:form>
        </f:view>
    </h:body>
</html>

Crud/Crud-war/web/editar.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Editar</title>
    </h:head>
    <h:body>
        <f:view>
            <h:form>
                <h1><h:outputText value="Editar"/></h1>
                <h:panelGrid columns="2">
                    <h:outputLabel value="Cod:" for="cod" />
                    <h:inputText id="cod" readonly="true" value="#{usuarioController.u.cod}" title="Cod" required="true" 
                                 requiredMessage="The Cod field is required."/>
                    <h:outputLabel value="Nom:" for="nom" />
                    <h:inputText id="nom" value="#{usuarioController.u.nom}" title="Nom" />
                    <h:outputLabel value="Edad:" for="edad" />
                    <h:inputText id="edad" value="#{usuarioController.u.edad}" title="Edad" />
                    <h:outputLabel value="Tel:" for="tel" />
                    <h:inputText id="tel" value="#{usuarioController.u.tel}" title="Tel" />
                    <h:commandButton value="Guardar" action="#{usuarioController.edit()}"></h:commandButton>
                </h:panelGrid>
            </h:form>
        </f:view>

    </h:body>
</html>

Crud/Crud-war/web/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:head>
        <title>Crud</title>
    </h:head>
    <h:body>
        <h:form>
            <h:link value="Agregar Nuevo Usuario" outcome="agregar"></h:link>
        <br></br>
        <h:dataTable var="u" value="#{usuarioController.findAll()}" border="1" 
                     cellpadding="2" cellspacing="2">
            <h:column>
                <f:facet name="header">ID</f:facet>
                <h:outputText value="#{u.cod}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">Nombre</f:facet>
                <h:outputText value="#{u.nom}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">Edad</f:facet>
                <h:outputText value="#{u.edad}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">Telefono</f:facet>
                <h:outputText value="#{u.tel}"></h:outputText>
            </h:column>
            <h:column>
                <f:facet name="header">Opcion</f:facet>
                <h:commandLink value="Borrar" action="#{usuarioController.delete(u)}" 
                               onclick="return confirm('Estas Seguro ?')">
                </h:commandLink> | 
                <h:commandLink value="Editar" action="#{usuarioController.edit(u)}" >
                </h:commandLink>
            </h:column>
        </h:dataTable>
        </h:form>        
    </h:body>
</html>